const carCityType = [
    {
        value:'0101',
        name:'冀A',
        explain:'石家庄市',
    },
    {
        value:'0102',
        name:'冀B',
        explain:'唐山市'
    },{
        value:'0103',
        name:'冀C',
        explain:'秦皇岛市'
    },{
        value:'0104',
        name:'冀D',
        explain:'邯郸市'
    },{
        value:'0105',
        name:'冀E',
        explain:'邢台市'
    },{
        value:'0106',
        name:'冀F',
        explain:'保定市'
    },{
        value:'0107',
        name:'冀G',
        explain:'张家口市'
    },{
        value:'0108',
        name:'冀H',
        explain:'承德市'
    },{
        value:'0109',
        name:'冀J',
        explain:'沧州市'
    },{
        value:'0110',
        name:'冀R',
        explain:'廊坊市'
    },{
        value:'0111',
        name:'冀T',
        explain:'衡水市'
    },{
        value:'0201',
        name:'宁A',
        explain:'银川市'
    },{
        value:'0202',
        name:'宁B',
        explain:'石嘴山市'
    },{
        value:'0203',
        name:'宁C',
        explain:'吴忠市'
    },{
        value:'0204',
        name:'宁D',
        explain:'固原市'
    },{
        value:'0205',
        name:'宁E',
        explain:'中卫市'
    },{
        value:'0301',
        name:'桂A',
        explain:'南宁市'
    },{
        value:'0302',
        name:'桂B',
        explain:'柳州市'
    },{
        value:'0303',
        name:'桂C',
        explain:'桂林市（六区加阳朔）'
    },{
        value:'0304',
        name:'桂D',
        explain:'梧州市'
    },{
        value:'0305',
        name:'桂E',
        explain:'北海市'
    },{
        value:'0306',
        name:'桂F',
        explain:'崇左市'
    },{
        value:'0307',
        name:'桂G',
        explain:'来宾市'
    },{
        value:'0308',
        name:'桂H',
        explain:'桂林市下辖县市（除阳朔）'
    },{
        value:'0309',
        name:'桂J',
        explain:'贺州市'
    },{
        value:'0310',
        name:'桂K',
        explain:'玉林市'
    },{
        value:'0311',
        name:'桂L',
        explain:'百色市'
    },{
        value:'0312',
        name:'桂M',
        explain:'河池市'
    },{
        value:'0313',
        name:'桂N',
        explain:'钦州市'
    },{
        value:'0314',
        name:'桂P',
        explain:'防城港市'
    },{
        value:'0315',
        name:'桂R',
        explain:'贵港市'
    },{
        value:'0401',
        name:'皖A',
        explain:'合肥市'
    },{
        value:'0402',
        name:'皖B',
        explain:'芜湖市'
    },{
        value:'0403',
        name:'皖C',
        explain:'蚌埠市'
    },{
        value:'0404',
        name:'皖D',
        explain:'淮南市'
    },{
        value:'0405',
        name:'皖E',
        explain:'马鞍山市'
    },{
        value:'0406',
        name:'皖F',
        explain:'淮北市'
    },{
        value:'0407',
        name:'皖G',
        explain:'铜陵市'
    },{
        value:'0408',
        name:'皖H',
        explain:'安庆市'
    },{
        value:'0409',
        name:'皖J',
        explain:'黄山市'
    },{
        value:'0410',
        name:'皖K',
        explain:'阜阳市'
    },{
        value:'0411',
        name:'皖L',
        explain:'宿州市'
    },{
        value:'0412',
        name:'皖M',
        explain:'滁州市'
    },{
        value:'0413',
        name:'皖N',
        explain:'六安市'
    },{
        value:'0414',
        name:'皖P',
        explain:'宣城市'
    },{
        value:'0415',
        name:'皖R',
        explain:'池州市'
    },{
        value:'0416',
        name:'皖S',
        explain:'亳州市'
    },{
        value:'0501',
        name:'蒙A',
        explain:'呼和浩特市'
    },{
        value:'0502',
        name:'蒙B',
        explain:'包头市'
    },{
        value:'0503',
        name:'蒙C',
        explain:'乌海市'
    },{
        value:'0504',
        name:'蒙D',
        explain:'赤峰市'
    },{
        value:'0505',
        name:'蒙E',
        explain:'呼伦贝尔市'
    },{
        value:'0506',
        name:'蒙F',
        explain:'兴安盟'
    },{
        value:'0507',
        name:'蒙G',
        explain:'通辽市'
    },{
        value:'0508',
        name:'蒙H',
        explain:'锡林郭勒盟'
    },{
        value:'0509',
        name:'蒙J',
        explain:'乌兰察布市'
    },{
        value:'0510',
        name:'蒙K',
        explain:'鄂尔多斯市'
    },{
        value:'0511',
        name:'蒙L',
        explain:'巴彦淖尔市'
    },{
        value:'0512',
        name:'蒙M',
        explain:'阿拉善盟'
    },{
        value:'0601',
        name:'辽A',
        explain:'沈阳市'
    },{
        value:'0602',
        name:'辽B',
        explain:'大连市'
    },{
        value:'0603',
        name:'辽C',
        explain:'鞍山市'
    },{
        value:'0604',
        name:'辽D',
        explain:'抚顺市'
    },{
        value:'0605',
        name:'辽E',
        explain:'本溪市'
    },{
        value:'0606',
        name:'辽F',
        explain:'丹东市'
    },{
        value:'0607',
        name:'辽G',
        explain:'锦州市'
    },{
        value:'0608',
        name:'辽H',
        explain:'营口市'
    },{
        value:'0609',
        name:'辽J',
        explain:'阜新市'
    },{
        value:'0610',
        name:'辽K',
        explain:'辽阳市'
    },{
        value:'0611',
        name:'辽L',
        explain:'盘锦市'
    },{
        value:'0612',
        name:'辽M',
        explain:'铁岭市'
    },{
        value:'0613',
        name:'辽N',
        explain:'朝阳市'
    },{
        value:'0614',
        name:'辽P',
        explain:'葫芦岛市'
    },{
        value:'0701',
        name:'晋A',
        explain:'太原市'
    },{
        value:'0702',
        name:'晋B',
        explain:'大同市'
    },{
        value:'0703',
        name:'晋C',
        explain:'阳泉市'
    },{
        value:'0704',
        name:'晋D',
        explain:'长治市'
    },{
        value:'0705',
        name:'晋E',
        explain:'晋城市'
    },{
        value:'0706',
        name:'晋F',
        explain:'朔州市'
    },{
        value:'0707',
        name:'晋H',
        explain:'忻州市'
    },{
        value:'0708',
        name:'晋J',
        explain:'吕梁市'
    },{
        value:'0709',
        name:'晋K',
        explain:'晋中市'
    },{
        value:'0710',
        name:'晋L',
        explain:'临汾市'
    },{
        value:'0711',
        name:'晋M',
        explain:'运城市'
    },{
        value:'0712',
        name:'晋N',
        explain:'山西省外籍人士和三资企业'
    },{
        value:'0801',
        name:'渝A',
        explain:'重庆市'
    },{
        value:'0802',
        name:'渝B',
        explain:'重庆市'
    },{
        value:'0803',
        name:'渝C',
        explain:'重庆市'
    },{
        value:'0804',
        name:'渝D',
        explain:'重庆市'
    },{
        value:'0805',
        name:'渝F',
        explain:'重庆市'
    },{
        value:'0806',
        name:'渝G',
        explain:'重庆市'
    },{
        value:'0807',
        name:'渝H',
        explain:'重庆市'
    },{
        value:'0901',
        name:'粤A',
        explain:'广州市'
    },{
        value:'0902',
        name:'粤B',
        explain:'深圳市'
    },{
        value:'0903',
        name:'粤C',
        explain:'珠海市'
    },{
        value:'0904',
        name:'粤D',
        explain:'汕头市'
    },{
        value:'0905',
        name:'粤E',
        explain:'佛山市'
    },{
        value:'0906',
        name:'粤F',
        explain:'韶关市'
    },{
        value:'0907',
        name:'粤G',
        explain:'湛江市'
    },{
        value:'0908',
        name:'粤H',
        explain:'肇庆市'
    },{
        value:'0909',
        name:'粤J',
        explain:'江门市'
    },{
        value:'0910',
        name:'粤K',
        explain:'茂名市'
    },{
        value:'0911',
        name:'粤L',
        explain:'惠州市'
    },{
        value:'0912',
        name:'粤M',
        explain:'梅州市'
    },{
        value:'0913',
        name:'粤N',
        explain:'汕尾市'
    },{
        value:'0914',
        name:'粤P',
        explain:'河源市'
    },{
        value:'0915',
        name:'粤Q',
        explain:'阳江市'
    },{
        value:'0916',
        name:'粤R',
        explain:'清远市'
    },{
        value:'0917',
        name:'粤S',
        explain:'东莞市'
    },{
        value:'0918',
        name:'粤T',
        explain:'中山市'
    },{
        value:'0919',
        name:'粤U',
        explain:'潮州市'
    },{
        value:'0920',
        name:'粤V',
        explain:'揭阳市'
    },{
        value:'0921',
        name:'粤W',
        explain:'云浮市'
    },{
        value:'0922',
        name:'粤X',
        explain:'[原佛山市顺德区]'
    },{
        value:'0923',
        name:'粤Y',
        explain:'[原佛山市南海区]'
    },{
        value:'0924',
        name:'粤Z',
        explain:'港澳进入内地车辆'
    },{
        value:'1001',
        name:'琼A',
        explain:'海口市'
    },{
        value:'1002',
        name:'琼B',
        explain:'三亚市'
    },{
        value:'1003',
        name:'琼C',
        explain:'琼海市、文昌市、万宁市、定安县、屯昌县、澄迈县、临高县'
    },{
        value:'1004',
        name:'琼D',
        explain:'五指山市、东方市、白沙县、昌江县、乐东县、陵水县、保亭县、琼中县'
    },{
        value:'1005',
        name:'琼E',
        explain:'洋浦开发区'
    },{
        value:'1006',
        name:'琼F',
        explain:'儋州市'
    },{
        value:'1101',
        name:'京A',
        explain:'北京市'
    },{
        value:'1102',
        name:'京B',
        explain:'北京市出租汽车'
    },{
        value:'1103',
        name:'京C',
        explain:'北京市'
    },{
        value:'1104',
        name:'京D',
        explain:'暂未发放'
    },{
        value:'1105',
        name:'京E',
        explain:'北京市'
    },{
        value:'1106',
        name:'京F',
        explain:'北京市'
    },{
        value:'1107',
        name:'京G',
        explain:'北京市郊区县'
    },{
        value:'1108',
        name:'京H',
        explain:'北京市'
    },{
        value:'1109',
        name:'京J',
        explain:'北京市'
    },{
        value:'1110',
        name:'京K',
        explain:'北京市'
    },{
        value:'1111',
        name:'京L',
        explain:'北京市'
    },{
        value:'1112',
        name:'京M',
        explain:'北京市'
    },{
        value:'1113',
        name:'京N',
        explain:'北京市'
    },{
        value:'1114',
        name:'京P',
        explain:'北京市'
    },{
        value:'1115',
        name:'京Q',
        explain:'北京市'
    },{
        value:'1116',
        name:'京Y',
        explain:'北京市郊区县'
    },{
        value:'1201',
        name:'新A',
        explain:'乌鲁木齐市'
    },{
        value:'1202',
        name:'新B',
        explain:'昌吉回族自治州、五家渠市'
    },{
        value:'1203',
        name:'新C',
        explain:'石河子市'
    },{
        value:'1204',
        name:'新D',
        explain:'奎屯市、胡杨河市'
    },{
        value:'1205',
        name:'新E',
        explain:'博尔塔拉蒙古自治州、双河市'
    },{
        value:'1206',
        name:'新F',
        explain:'伊犁哈萨克自治州直辖县市（除奎屯市）、可克达拉市'
    },{
        value:'1207',
        name:'新G',
        explain:'伊犁哈萨克自治州塔城地区'
    },{
        value:'1208',
        name:'新H',
        explain:'伊犁哈萨克自治州阿勒泰地区、北屯市'
    },{
        value:'1209',
        name:'新J',
        explain:'克拉玛依市'
    },{
        value:'1210',
        name:'新K',
        explain:'吐鲁番市'
    },{
        value:'1211',
        name:'新L',
        explain:'哈密市'
    },{
        value:'1212',
        name:'新M',
        explain:'巴音郭楞蒙古自治州、铁门关市'
    },{
        value:'1213',
        name:'新N',
        explain:'阿克苏地区、阿拉尔市'
    },{
        value:'1214',
        name:'新P',
        explain:'克孜勒苏柯尔克孜自治州'
    },{
        value:'1215',
        name:'新Q',
        explain:'喀什地区、图木舒克市'
    },{
        value:'1216',
        name:'新R',
        explain:'和田地区'
    },{
        value:'1217',
        name:'新S',
        explain:'昆玉市'
    },{
        value:'1301',
        name:'黑A',
        explain:'哈尔滨市市区（除双城区）'
    },{
        value:'1302',
        name:'黑B',
        explain:'齐齐哈尔市'
    },{
        value:'1303',
        name:'黑C',
        explain:'牡丹江市'
    },{
        value:'1304',
        name:'黑D',
        explain:'佳木斯市'
    },{
        value:'1305',
        name:'黑E',
        explain:'大庆市'
    },{
        value:'1306',
        name:'黑F',
        explain:'伊春市'
    },{
        value:'1307',
        name:'黑G',
        explain:'鸡西市'
    },{
        value:'1308',
        name:'黑H',
        explain:'鹤岗市'
    },{
        value:'1309',
        name:'黑J',
        explain:'双鸭山市'
    },{
        value:'1310',
        name:'黑K',
        explain:'七台河市'
    },{
        value:'1311',
        name:'黑L',
        explain:'哈尔滨市下辖县和双城区'
    },{
        value:'1312',
        name:'黑M',
        explain:'绥化市'
    },{
        value:'1313',
        name:'黑N',
        explain:'黑河市'
    },{
        value:'1314',
        name:'黑P',
        explain:'大兴安岭地区'
    },{
        value:'1315',
        name:'黑R',
        explain:'农垦系统'
    },{
        value:'1401',
        name:'云A',
        explain:'昆明市（东川区使用云A-V）'
    },{
        value:'1402',
        name:'云C',
        explain:'昭通市'
    },{
        value:'1403',
        name:'云D',
        explain:'曲靖市'
    },{
        value:'1404',
        name:'云E',
        explain:'楚雄彝族自治州'
    },{
        value:'1405',
        name:'云F',
        explain:'玉溪市'
    },{
        value:'1406',
        name:'云G',
        explain:'红河哈尼族彝族自治州'
    },{
        value:'1407',
        name:'云H',
        explain:'文山壮族苗族自治州'
    },{
        value:'1408',
        name:'云J',
        explain:'普洱市'
    },{
        value:'1409',
        name:'云K',
        explain:'西双版纳傣族自治州'
    },{
        value:'1410',
        name:'云L',
        explain:'大理白族自治州'
    },{
        value:'1411',
        name:'云M',
        explain:'保山市'
    },{
        value:'1412',
        name:'云N',
        explain:'德宏傣族景颇族自治州'
    },{
        value:'1413',
        name:'云P',
        explain:'丽江市'
    },{
        value:'1414',
        name:'云Q',
        explain:'怒江傈僳族自治州'
    },{
        value:'1415',
        name:'云R',
        explain:'迪庆藏族自治州'
    },{
        value:'1416',
        name:'云S',
        explain:'临沧市'
    },{
        value:'1501',
        name:'赣A',
        explain:'南昌市'
    },{
        value:'1502',
        name:'赣B',
        explain:'赣州市'
    },{
        value:'1503',
        name:'赣C',
        explain:'宜春市'
    },{
        value:'1504',
        name:'赣D',
        explain:'吉安市'
    },{
        value:'1505',
        name:'赣E',
        explain:'上饶市'
    },{
        value:'1506',
        name:'赣F',
        explain:'抚州市'
    },{
        value:'1507',
        name:'赣G',
        explain:'九江市'
    },{
        value:'1508',
        name:'赣H',
        explain:'景德镇市'
    },{
        value:'1509',
        name:'赣J',
        explain:'萍乡市'
    },{
        value:'1510',
        name:'赣K',
        explain:'新余市'
    },{
        value:'1511',
        name:'赣L',
        explain:'鹰潭市'
    },{
        value:'1512',
        name:'赣M',
        explain:'南昌市增补、省直系统'
    },{
        value:'1601',
        name:'苏A',
        explain:'南京市'
    },{
        value:'1602',
        name:'苏B',
        explain:'无锡市'
    },{
        value:'1603',
        name:'苏C',
        explain:'徐州市'
    },{
        value:'1604',
        name:'苏D',
        explain:'常州市'
    },{
        value:'1605',
        name:'苏E',
        explain:'苏州市'
    },{
        value:'1606',
        name:'苏F',
        explain:'南通市'
    },{
        value:'1607',
        name:'苏G',
        explain:'连云港市'
    },{
        value:'1608',
        name:'苏H',
        explain:'淮安市'
    },{
        value:'1609',
        name:'苏J',
        explain:'盐城市'
    },{
        value:'1610',
        name:'苏K',
        explain:'扬州市'
    },{
        value:'1611',
        name:'苏L',
        explain:'镇江市'
    },{
        value:'1612',
        name:'苏M',
        explain:'泰州市'
    },{
        value:'1613',
        name:'苏N',
        explain:'宿迁市'
    },{
        value:'1614',
        name:'苏U',
        explain:'苏州市增补'
    },{
        value:'1701',
        name:'浙A',
        explain:'杭州市'
    },{
        value:'1702',
        name:'浙B',
        explain:'宁波市'
    },{
        value:'1703',
        name:'浙C',
        explain:'温州市'
    },{
        value:'1704',
        name:'浙D',
        explain:'绍兴市'
    },{
        value:'1705',
        name:'浙E',
        explain:'湖州市'
    },{
        value:'1706',
        name:'浙F',
        explain:'嘉兴市'
    },{
        value:'1707',
        name:'浙G',
        explain:'金华市'
    },{
        value:'1708',
        name:'浙H',
        explain:'衢州市'
    },{
        value:'1709',
        name:'浙J',
        explain:'台州市'
    },{
        value:'1710',
        name:'浙K',
        explain:'丽水市'
    },{
        value:'1711',
        name:'浙L',
        explain:'舟山市'
    },{
        value:'1801',
        name:'贵A',
        explain:'贵阳市'
    },{
        value:'1802',
        name:'贵B',
        explain:'六盘水市'
    },{
        value:'1803',
        name:'贵C',
        explain:'遵义市'
    },{
        value:'1804',
        name:'贵D',
        explain:'铜仁市'
    },{
        value:'1805',
        name:'贵E',
        explain:'黔西南布依族苗族自治州'
    },{
        value:'1806',
        name:'贵F',
        explain:'毕节市'
    },{
        value:'1807',
        name:'贵G',
        explain:'安顺市'
    },{
        value:'1808',
        name:'贵H',
        explain:'黔东南苗族侗族自治州'
    },{
        value:'1809',
        name:'贵J',
        explain:'黔南布依族苗族自治州'
    },{
        value:'1901',
        name:'川A',
        explain:'成都市'
    },{
        value:'1902',
        name:'川B',
        explain:'绵阳市'
    },{
        value:'1903',
        name:'川C',
        explain:'自贡市'
    },{
        value:'1904',
        name:'川D',
        explain:'攀枝花市'
    },{
        value:'1905',
        name:'川E',
        explain:'泸州市'
    },{
        value:'1906',
        name:'川F',
        explain:'德阳市'
    },{
        value:'1907',
        name:'川G',
        explain:'成都市增补'
    },{
        value:'1908',
        name:'川H',
        explain:'广元市'
    },{
        value:'1909',
        name:'川J',
        explain:'遂宁市'
    },{
        value:'1910',
        name:'川K',
        explain:'内江市'
    },{
        value:'1911',
        name:'川L',
        explain:'乐山市'
    },{
        value:'1912',
        name:'川M',
        explain:'资阳市'
    },{
        value:'1913',
        name:'川Q',
        explain:'宜宾市'
    },{
        value:'1914',
        name:'川R',
        explain:'南充市'
    },{
        value:'1915',
        name:'川S',
        explain:'达州市'
    },{
        value:'1916',
        name:'川T',
        explain:'雅安市'
    },{
        value:'1917',
        name:'川U',
        explain:'阿坝藏族羌族自治州'
    },{
        value:'1918',
        name:'川V',
        explain:'甘孜藏族自治州'
    },{
        value:'1919',
        name:'川W',
        explain:'凉山彝族自治州'
    },{
        value:'1920',
        name:'川X',
        explain:'广安市'
    },{
        value:'1921',
        name:'川Y',
        explain:'巴中市'
    },{
        value:'1922',
        name:'川Z',
        explain:'眉山市'
    },{
        value:'2001',
        name:'青A',
        explain:'西宁市'
    },{
        value:'2002',
        name:'青B',
        explain:'海东市'
    },{
        value:'2003',
        name:'青C',
        explain:'海北藏族自治州'
    },{
        value:'2004',
        name:'青D',
        explain:'黄南藏族自治州'
    },{
        value:'2005',
        name:'青E',
        explain:'海南藏族自治州'
    },{
        value:'2006',
        name:'青F',
        explain:'果洛藏族自治州'
    },{
        value:'2007',
        name:'青G',
        explain:'玉树藏族自治州'
    },{
        value:'2008',
        name:'青H',
        explain:'海西蒙古族藏族自治州'
    },{
        value:'2101',
        name:'津A',
        explain:'天津市'
    },{
        value:'2102',
        name:'津B',
        explain:'天津市'
    },{
        value:'2103',
        name:'津C',
        explain:'天津市'
    },{
        value:'2104',
        name:'津D',
        explain:'天津市'
    },{
        value:'2105',
        name:'津E',
        explain:'天津市出租汽车'
    },{
        value:'2106',
        name:'津F',
        explain:'天津市'
    },{
        value:'2107',
        name:'津G',
        explain:'天津市'
    },{
        value:'2108',
        name:'津H',
        explain:'天津市'
    },{
        value:'2109',
        name:'津J',
        explain:'天津市'
    },{
        value:'2110',
        name:'津K',
        explain:'天津市'
    },{
        value:'2111',
        name:'津L',
        explain:'天津市'
    },{
        value:'2112',
        name:'津M',
        explain:'天津市'
    },{
        value:'2113',
        name:'津N',
        explain:'天津市'
    },{
        value:'2114',
        name:'津Q',
        explain:'天津市'
    },{
        value:'2115',
        name:'津R',
        explain:'天津市'
    },{
        value:'2201',
        name:'鄂A',
        explain:'武汉市'
    },{
        value:'2202',
        name:'鄂B',
        explain:'黄石市'
    },{
        value:'2203',
        name:'鄂C',
        explain:'十堰市'
    },{
        value:'2204',
        name:'鄂D',
        explain:'荆州市'
    },{
        value:'2205',
        name:'鄂E',
        explain:'宜昌市'
    },{
        value:'2206',
        name:'鄂F',
        explain:'襄阳市'
    },{
        value:'2207',
        name:'鄂G',
        explain:'鄂州市'
    },{
        value:'2208',
        name:'鄂H',
        explain:'荆门市'
    },{
        value:'2209',
        name:'鄂J',
        explain:'黄冈市'
    },{
        value:'2210',
        name:'鄂K',
        explain:'孝感市'
    },{
        value:'2211',
        name:'鄂L',
        explain:'咸宁市'
    },{
        value:'2222',
        name:'鄂M',
        explain:'仙桃市'
    },{
        value:'2213',
        name:'鄂N',
        explain:'潜江市'
    },{
        value:'2214',
        name:'鄂P',
        explain:'神农架林区'
    },{
        value:'2215',
        name:'鄂Q',
        explain:'恩施土家族苗族自治州'
    },{
        value:'2216',
        name:'鄂R',
        explain:'天门市'
    },{
        value:'2217',
        name:'鄂S',
        explain:'随州市'
    },{
        value:'2301',
        name:'湘A',
        explain:'长沙市'
    },{
        value:'2302',
        name:'湘B',
        explain:'株洲市'
    },{
        value:'2303',
        name:'湘C',
        explain:'湘潭市'
    },{
        value:'2304',
        name:'湘D',
        explain:'衡阳市'
    },{
        value:'2305',
        name:'湘E',
        explain:'邵阳市'
    },{
        value:'2306',
        name:'湘F',
        explain:'岳阳市'
    },{
        value:'2307',
        name:'湘G',
        explain:'张家界市'
    },{
        value:'2308',
        name:'湘H',
        explain:'益阳市'
    },{
        value:'2309',
        name:'湘J',
        explain:'常德市'
    },{
        value:'2310',
        name:'湘K',
        explain:'娄底市'
    },{
        value:'2311',
        name:'湘L',
        explain:'郴州市'
    },{
        value:'2312',
        name:'湘M',
        explain:'永州市'
    },{
        value:'2323',
        name:'湘N',
        explain:'怀化市'
    },{
        value:'2314',
        name:'湘U',
        explain:'湘西土家族苗族自治州'
    },{
        value:'2315',
        name:'湘S',
        explain:'省直系统'
    },{
        value:'2401',
        name:'豫A',
        explain:'郑州市'
    },{
        value:'2402',
        name:'豫B',
        explain:'开封市'
    },{
        value:'2403',
        name:'豫C',
        explain:'洛阳市'
    },{
        value:'2404',
        name:'豫D',
        explain:'平顶山市'
    },{
        value:'2405',
        name:'豫E',
        explain:'安阳市'
    },{
        value:'2406',
        name:'豫F',
        explain:'鹤壁市'
    },{
        value:'2407',
        name:'豫G',
        explain:'新乡市'
    },{
        value:'2408',
        name:'豫H',
        explain:'焦作市'
    },{
        value:'2409',
        name:'豫J',
        explain:'濮阳市'
    },{
        value:'2410',
        name:'豫K',
        explain:'许昌市'
    },{
        value:'2411',
        name:'豫L',
        explain:'漯河市'
    },{
        value:'2412',
        name:'豫M',
        explain:'三门峡市'
    },{
        value:'2413',
        name:'豫N',
        explain:'商丘市'
    },{
        value:'2414',
        name:'豫P',
        explain:'周口市'
    },{
        value:'2415',
        name:'豫Q',
        explain:'驻马店市'
    },{
        value:'2416',
        name:'豫R',
        explain:'南阳市'
    },{
        value:'2417',
        name:'豫S',
        explain:'信阳市'
    },{
        value:'2418',
        name:'豫U',
        explain:'济源市'
    },{
        value:'2501',
        name:'吉A',
        explain:'长春市'
    },{
        value:'2502',
        name:'吉B',
        explain:'吉林市'
    },{
        value:'2503',
        name:'吉C',
        explain:'四平市'
    },{
        value:'2504',
        name:'吉D',
        explain:'辽源市'
    },{
        value:'2505',
        name:'吉E',
        explain:'通化市'
    },{
        value:'2506',
        name:'吉F',
        explain:'白山市'
    },{
        value:'2507',
        name:'吉G',
        explain:'白城市'
    },{
        value:'2601',
        name:'甘A',
        explain:'兰州市'
    },{
        value:'2602',
        name:'甘B',
        explain:'嘉峪关市'
    },{
        value:'2603',
        name:'甘C',
        explain:'金昌市'
    },{
        value:'2604',
        name:'甘D',
        explain:'白银市'
    },{
        value:'2605',
        name:'甘E',
        explain:'天水市'
    },{
        value:'2606',
        name:'甘F',
        explain:'酒泉市'
    },{
        value:'2607',
        name:'甘G',
        explain:'张掖市'
    },{
        value:'2608',
        name:'甘H',
        explain:'武威市'
    },{
        value:'2609',
        name:'甘J',
        explain:'定西市'
    },{
        value:'2610',
        name:'甘K',
        explain:'陇南市'
    },{
        value:'2611',
        name:'甘L',
        explain:'平凉市'
    },{
        value:'2612',
        name:'甘M',
        explain:'庆阳市'
    },{
        value:'2613',
        name:'甘N',
        explain:'临夏回族自治州'
    },{
        value:'2614',
        name:'甘P',
        explain:'甘南藏族自治州'
    },{
        value:'2701',
        name:'闽A',
        explain:'福州市'
    },{
        value:'2702',
        name:'闽B',
        explain:'莆田市'
    },{
        value:'2703',
        name:'闽C',
        explain:'泉州市'
    },{
        value:'2704',
        name:'闽D',
        explain:'厦门市'
    },{
        value:'2705',
        name:'闽E',
        explain:'漳州市'
    },{
        value:'2706',
        name:'闽F',
        explain:'龙岩市'
    },{
        value:'2707',
        name:'闽G',
        explain:'三明市'
    },{
        value:'2708',
        name:'闽H',
        explain:'南平市'
    },{
        value:'2709',
        name:'闽J',
        explain:'宁德市'
    },{
        value:'2710',
        name:'闽K',
        explain:'省直系统、平潭综合实验区'
    },{
        value:'2801',
        name:'陕A',
        explain:'西安市'
    },{
        value:'2802',
        name:'陕B',
        explain:'铜川市'
    },{
        value:'2803',
        name:'陕C',
        explain:'宝鸡市'
    },{
        value:'2804',
        name:'陕D',
        explain:'咸阳市'
    },{
        value:'2805',
        name:'陕E',
        explain:'渭南市'
    },{
        value:'2806',
        name:'陕F',
        explain:'汉中市'
    },{
        value:'2807',
        name:'陕G',
        explain:'安康市'
    },{
        value:'2808',
        name:'陕H',
        explain:'商洛市'
    },{
        value:'2809',
        name:'陕J',
        explain:'延安市'
    },{
        value:'2810',
        name:'陕K',
        explain:'榆林市'
    },{
        value:'2811',
        name:'陕V',
        explain:'杨凌农业示范区'
    },{
        value:'2901',
        name:'鲁A',
        explain:'济南市（除莱芜区、钢城区）'
    },{
        value:'2902',
        name:'鲁B',
        explain:'青岛市'
    },{
        value:'2903',
        name:'鲁C',
        explain:'淄博市'
    },{
        value:'2904',
        name:'鲁D',
        explain:'枣庄市'
    },{
        value:'2905',
        name:'鲁E',
        explain:'东营市'
    },{
        value:'2906',
        name:'鲁F',
        explain:'烟台市'
    },{
        value:'2907',
        name:'鲁G',
        explain:'潍坊市'
    },{
        value:'2908',
        name:'鲁H',
        explain:'济宁市'
    },{
        value:'2909',
        name:'鲁J',
        explain:'泰安市'
    },{
        value:'2910',
        name:'鲁K',
        explain:'威海市'
    },{
        value:'2911',
        name:'鲁L',
        explain:'日照市'
    },{
        value:'2912',
        name:'鲁M',
        explain:'滨州市'
    },{
        value:'2913',
        name:'鲁N',
        explain:'德州市'
    },{
        value:'2914',
        name:'鲁P',
        explain:'聊城市'
    },{
        value:'2915',
        name:'鲁Q',
        explain:'临沂市'
    },{
        value:'2916',
        name:'鲁R',
        explain:'菏泽市'
    },{
        value:'2917',
        name:'鲁S',
        explain:'济南市莱芜区、钢城区'
    },{
        value:'2918',
        name:'鲁U',
        explain:'青岛市增补'
    },{
        value:'2919',
        name:'鲁V',
        explain:'潍坊市增补'
    },{
        value:'2920',
        name:'鲁W',
        explain:'省直系统'
    },{
        value:'2921',
        name:'鲁Y',
        explain:'烟台市增补'
    },{
        value:'3001',
        name:'藏A',
        explain:'拉萨市'
    },{
        value:'3002',
        name:'藏B',
        explain:'昌都市'
    },{
        value:'3003',
        name:'藏C',
        explain:'山南市'
    },{
        value:'3004',
        name:'藏D',
        explain:'日喀则市'
    },{
        value:'3005',
        name:'藏E',
        explain:'那曲市'
    },{
        value:'3006',
        name:'藏F',
        explain:'阿里地区'
    },{
        value:'3007',
        name:'藏G',
        explain:'林芝市'
    },{
        value:'3008',
        name:'藏H',
        explain:'驻四川省天全县车辆管理所'
    },{
        value:'3009',
        name:'藏J',
        explain:'驻青海省格尔木市车辆管理所'
    },{
        value:'3101',
        name:'沪A',
        explain:'上海市'
    },{
        value:'3102',
        name:'沪B',
        explain:'上海市'
    },{
        value:'3103',
        name:'沪C',
        explain:'上海市(郊区牌照，不能进入以S20环线以内)'
    },{
        value:'3104',
        name:'沪D',
        explain:'上海市'
    },{
        value:'3105',
        name:'沪E',
        explain:'上海市'
    },{
        value:'3106',
        name:'沪F',
        explain:'上海市'
    },{
        value:'3107',
        name:'沪G',
        explain:'上海市'
    },{
        value:'3108',
        name:'沪H',
        explain:'上海市'
    },{
        value:'3109',
        name:'沪J',
        explain:'上海市'
    },{
        value:'3110',
        name:'沪K',
        explain:'上海市'
    },{
        value:'3111',
        name:'沪L',
        explain:'上海市'
    },{
        value:'3112',
        name:'沪M',
        explain:'上海市'
    },{
        value:'3113',
        name:'沪N',
        explain:'上海市'
    },{
        value:'3114',
        name:'沪R',
        explain:'[原崇明、长兴、横沙专用车牌，不能驶出三岛]'
    }
]
export default carCityType;